config/routes.rb
Rails.application.routes.draw do

  get 'set_language/english'

  get 'set_language/ukraine'

  mount RailsAdmin::Engine => '/company/dashboard/admin', as: 'rails_admin'
  
  get "/:page" => "pages#show"
  
  resources "contacts", only: [:new, :create]
  get "/company/contacts" => "contacts#new"


  root "pages#show", page: "home"

  scope '/company' do
    resources :vacancies
  end

  scope '/company/' do
    resources :novelties
  end

  scope '/company/' do
    resources :events
  end
    
end

app/models/contact.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)`[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class Contact < ActiveRecord::Base
	validates :name, presence: true, length: {in: 2..25}
	validates :email, presence: true, email: true
	validates :message, presence: true, length: {in: 5..250}
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :title, presence: true, length: {in: 2..25}
	validates :description, presence: true, length: {in: 5..2500}
	validates :start, presence: true
	validates :end, presence: true
end

app/models/novelty.rb
class Novelty < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "700x500#", small: "350x250#"}
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	validates :title, presence: true, length: {in: 2..25}
	validates :description, presence: true, length: {in: 5..2500}
	validates :image, presence: true
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
	validates :name, presence: true, length: {in: 2..25}
	validates :country, presence: true, length: {in: 2..25}
	validates :description, presence: true, length: {in: 5..2500}
	validates :requirements, presence: true, length: {in: 5..2500}
	validates :responsibilities, presence: true, length: {in: 5..2500}
	validates :tools_and_techonologies, presence: true, length: {in: 5..2500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale
 
  private
  def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contact_params)
		
		if @contact.save
			redirect_to "/company/contacts"
		else
			redirect_to "/company/contacts"
		end
	end

	private
		def contact_params
			params.require(:contact).permit(:name, :email, :subject, :message)
		end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :find_event, only: [:show, :edit, :update, :destroy]


	def index
		@events = Event.all.order("created_at DESC")
	end

	def show;end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(events_params)

		if @event.save
			redirect_to event_path(@event)
		else
			render 'new'
		end
	end

	def update
		if @event.update(events_params)
			redirect_to @event
		else
			render 'edit'
		end
	end

	def destroy
		@event.destroy
		redirect_to root_path
	end

	private 

		def find_event
			@event = Event.find(params[:id])
		end

		def events_params
			params.require(:event).permit(:title, :description, :start, :end)
		end
end

app/controllers/novelties_controller.rb
class NoveltiesController < ApplicationController
	before_action :find_novelty, only: [:show, :edit, :update, :destroy]


	def index
		@novelties = Novelty.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
	end

	def show
		@random_novelty = Novelty.where.not(id: @novelty).order("RANDOM()").first
	end

	def new
		@novelty = Novelty.new
	end

	def create
		@novelty = Novelty.new(novelties_params)

		if @novelty.save
			redirect_to novelty_path(@novelty)
		else
			render 'new'
		end
	end

	def update
		if @novelty.update(novelties_params)
			redirect_to @novelty
		else
			render 'edit'
		end
	end

	def destroy
		@novelty.destroy
		redirect_to root_path
	end

	private 

		def find_novelty
			@novelty = Novelty.find(params[:id])
		end

		def novelties_params
			params.require(:novelty).permit(:title, :description, :image)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
		if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
   	def valid_page?
     	File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.slim"))
    end
end

app/controllers/set_language_controller.rb
class SetLanguageController < ApplicationController
  def english
  	I18n.locale = :en
    set_session_and_redirect
  end

  def ukraine
  	I18n.locale = :ua
    set_session_and_redirect
  end

  private
  def set_session_and_redirect
    session[:locale] = I18n.locale
    redirect_to :back
    rescue ActionController::RedirectBackError
      redirect_to :root
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
	before_action :find_vacancy, only: [:show, :edit, :update, :destroy]

	def index
		@vacancies = Vacancy.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 1)
	end

	def new
		@vacancy = Vacancy.new
	end

	def show;end

	def create
		@vacancy = Vacancy.new(vacancy_params)

		if @vacancy.save
			redirect_to vacancy_path(@vacancy)
		else
			render 'new'
		end
	end

	def update
		if @vacancy.update(vacancy_params)
			redirect_to @vacancy
		else
			render 'edit'
		end
	end

	def destroy
		@vacancy.destroy
		redirect_to root_path
	end

	private
	def find_vacancy
		@vacancy = Vacancy.find(params[:id])
	end

	def vacancy_params
		params.require(:vacancy).permit(:name, :country, :city, :description, :requirements, :responsibilities, :tools_and_techonologies)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/set_language_helper.rb
module SetLanguageHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/contacts/new.html.slim
div class="carousel fade-carousel slide" data-ride="carousel" data-interval="2200" id="bs-carousel"

  ol class="carousel-indicators"
    li data-target="#bs-carousel" data-slide-to="0" class="active"
    li data-target="#bs-carousel" data-slide-to="1"
  
  div class="carousel-inner"
    div class="item slides active"
      div class="slide-4"
      div class="hero"
        hgroup
            h1 = t 'contact.show_page.build'   
    div class="item slides"
      div class="slide-5"
      div class="hero"    
        hgroup
            h1 = t 'contact.show_page.office'  

section id="contact"
    div class="container wow fadeInUp"
      div class="row"
        div class="col-md-12"
          h3 class="section-title" = t 'contact.show_page.cont'  
          hr
      
      div class="row"
        div class="col-md-3 col-md-push-2"
          div class="info"
            div
              i class="glyphicon glyphicon-map-marker"
              p 
                | A108 Adam Street
                br New York, NY 535022
            
            div
              i class="glyphicon glyphicon-envelope"
              p info@example.com
            br
            div
              i class="glyphicon glyphicon-earphone"
              p +1 5589 55488 55

        
        div class="col-md-5 col-md-push-2"
          div class="form"
            = form_for @contact do |f|
              .form_in
                = f.label "#{t'contact.show_page.name'}"
                = f.text_field :name, :autofocus => true, class: "form-control", placeholder: "#{t'contact.show_page.name'}"
              .form_in
                = f.label "#{t'contact.show_page.email'}"
                = f.text_field :email, class: "form-control", placeholder: "#{t'contact.show_page.email'}"
              .form_in
                = f.label "#{t'contact.show_page.subj'}"
                = f.text_field :subject, class: "form-control", placeholder: "#{t'contact.show_page.subj'}" 
              .form_in
                = f.label "#{t'contact.show_page.desc'}"
                = f.text_area :message, class: "form-control", placeholder: "#{t'contact.show_page.desc'}" 
              .form_in
                = f.submit "#{t'contact.show_page.send'}", remote: true, class:"btn button btn-block"

#google-map
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3024.8844088212463!2d-73.98975255333487!3d40.698543335037364!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a35da2fd673%3A0x218ed6cc00224ef8!2zQWRhbXMgU3QsIEJyb29rbHluLCBOWSAwNzAzMCwg0KHQv9C-0LvRg9GH0LXQvdGWINCo0YLQsNGC0Lgg0JDQvNC10YDQuNC60Lg!5e0!3m2!1suk!2sua!4v1489841068240" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/events/_form.html.slim
#form
	.wrapper_skinny

		= form_for @event do |f|
			#errors_wrapper
				- if @event.errors.any?
					h2 
						= pluralize(@event.errors.count, "error")
					ul
						- @event.errors.full_messages.each do |msg|
							p = msg
			.form_in
				= f.label "Event name:"
				= f.text_field :title, :autofocus => true, class: "form-control", placeholder: "Event name"
			.form_in
				= f.label "Event description:"
				= f.text_area :description, class: "form-control", placeholder: "Description"
			.form_in
				= f.label "Set event start date-time:"
				= f.datetime_select :start, { ampm: true, order: [:day, :month, :year] }, { class: "form-control" }
			.form_in
				= f.label "Set event end date-time:"
				= f.datetime_select :end, { ampm: true, order: [:day, :month, :year] }, { class: "form-control" }
			.form_in
				= f.submit "Create a event", remote: true, class:"btn button btn-block"

app/views/events/edit.html.slim
div class="container bg-overlay-events"
	div class="events-header container-fluid"
		h1
			strong Events

hr

= render 'form'

app/views/events/index.html.slim
div class="container bg-overlay-events"
	div class="events-header container-fluid"
				h1
					strong = t 'events.show_page.events'

hr

div class="container"
	div class="row"
		div class="col-md-8 col-md-offset-2"
			div id="calendar"

hr

app/views/events/new.html.slim
div class="container bg-overlay-events"
	div class="events-header container-fluid"
		h1
			strong Events

hr

= render 'form'

app/views/events/show.html.slim
div class="container bg-overlay-events"
	div class="events-header container-fluid"
		h1
			strong Events

div class="container"
	div class="row"
		div class="col-md-8 col-md-offset-2"
			div class="codrops-header container-fluid"
				h1 
					strong= @event.title
hr
div class="container"
	div class="row"
		div class="col-md-7 col-md-offset-3"
			h4
				strong Event start at:&nbsp;
				= @event.start.strftime('%H:%M, %b %d, %Y')
				| &nbsp;&nbsp;
				strong Event end at:&nbsp;
				= @event.end.strftime('%H:%M, %b %d, %Y')
		div class="row"
				div class="col-md-12"
					hr
					p.lead = @event.description.gsub(/[\n\r]/, "<br />").html_safe

app/views/layouts/application.html.slim
doctype html
html
	head
  	title Codestar
  	meta name="viewport" content="width=device-width, initial-scale=1"
  	= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  	= javascript_include_tag 'application', 'data-turbolinks-track' => true
  	= csrf_meta_tags
	body id="page-top"
    	nav id="mainNav" class="navbar navbar-default navbar-fixed-top"
        	div class="container-fluid"
            	div class="navbar-header"
                	button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    	<span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                	a class="navbar-brand page-scroll" href="/home" Code star

	            div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"
	                ul class="nav navbar-nav navbar-right"
	                    li
	                        a class="page-scroll" href="/about" = t 'application.show_page.about'
	                    li
	                        a class="page-scroll" href="/portfolio" = t 'application.show_page.portfolio'
	                    li
	                        a class="page-scroll" href="/company/vacancies" = t 'application.show_page.vacancy'
	                    li
	                        a class="page-scroll" href="/company/events" = t 'application.show_page.events'
	                    li
	                        a class="page-scroll" href="/company/novelties" = t 'application.show_page.novelties'
	                    li
	                        a class="page-scroll" href="/company/contacts" = t 'application.show_page.contact'
	                    li
	                    	= link_to_unless I18n.locale == :en, "en", set_language_english_path
	                    li
							= link_to_unless I18n.locale == :ua, "ua", set_language_ukraine_path
                  
		= yield

		footer id="footer"
		    div class="container"
		        div class="row"
		          div class="col-md-12"
		            div class="copyright"
		            	p 
		            		| &copy; Copyright, 
		            		strong All Rights Reserved
		            div class="credits"
		            	p By Roma Nest

app/views/novelties/_form.html.slim
#form
	.wrapper_skinny

		= form_for @novelty do |f|
			#errors_wrapper
				- if @novelty.errors.any?
					h2 
						= pluralize(@novelty.errors.count, "error")
					ul
						- @novelty.errors.full_messages.each do |msg|
							p = msg
			.form_in
				= f.label "Tile:"
				= f.text_field :title, :autofocus => true, class: "form-control", placeholder: "Title."
			.form_in
				= f.label "Description:"
				= f.text_area :description, class: "form-control", placeholder: "Description"
			.form_in
				= f.label "Upload image:"
				br
				span.btn.button.btn-file
					= f.label "Browse", class: "browse_image input-group", for: "file_field"
					= f.file_field :image, id: "file_field"
				#img_block
					img#img-upload /
			.form_in
				= f.submit "Create a vacancy", remote: true, class:"btn button btn-block"

app/views/novelties/edit.html.slim
h1 ololo

app/views/novelties/index.html.slim
div class="container bg-overlay-news"
div class="wrapper"
	div class="novelties"
		div class="codrops-header container-fluid"
			h1 
				strong= t 'novelty.show_page.novelty'
		hr
		div id="novelties"
			- @novelties.each do |novelty|
				div class="novelty"
					= image_tag novelty.image.url(:small)
					h2.linkss = link_to novelty.title, controller: "novelties", action: "show", id: novelty
		hr
		div class = "paginate_for"
			= will_paginate @vacancies

app/views/novelties/new.html.slim
div class="container bg-overlay-news"

div class="codrops-header container-fluid"
	h1 
		strong Creating Novelties

= render 'form'

app/views/novelties/show.html.slim
div class="container bg-overlay-news"
div class="wrapper"
	div class="novelties"
		hr
		div class="container"
			div class="row"
				div class="col-md-7"
					h1 
						strong Title: 
						= @novelty.title
					br
					= image_tag @novelty.image.url(:medium)
				div class="col-md-5"
					h1
						| Random novelty:
					br
					= link_to ( image_tag @random_novelty.image.url(:small) ), novelty_path(@random_novelty)
					h2.linkss= link_to @random_novelty.title, novelty_path(@random_novelty)
				div class="row"
					div class="col-md-12"
						hr
						p.lead = @novelty.description.gsub(/[\n\r]/, "<br />").html_safe
			hr

app/views/pages/about.html.slim
div class="carousel fade-carousel slide" data-ride="carousel" data-interval="2200" id="bs-carousel"

  ol class="carousel-indicators"
    li data-target="#bs-carousel" data-slide-to="0" class="active"
    li data-target="#bs-carousel" data-slide-to="1"
    li data-target="#bs-carousel" data-slide-to="2"
  
  div class="carousel-inner"
    div class="item slides active"
      div class="slide-1"
      div class="hero"
        hgroup
            h1 = t 'about.show_page.slide_1'      
            h3 = t 'about.show_page.slide_p' 
    div class="item slides"
      div class="slide-2"
      div class="hero"    
        hgroup
            h1 = t 'about.show_page.slide_2'   
            h3 = t 'about.show_page.slide_p' 
    div class="item slides"
      div class="slide-3"
      div class="hero"
        hgroup
            h1 = t 'about.show_page.slide_3'    
            h3 = t 'about.show_page.slide_p'   

div class="aboutus"
 div class="container"
	h3 = t 'about.show_page.inf'
	hr
	div class="col-md-7 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms"
		= image_tag("7.jpg", class: "img-responsive")
		h4 = t 'about.show_page.slogan'
		p = t 'about.show_page.slog_desc'
	div class="col-md-5 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms"
		div class="skill"
			h2 = t 'about.show_page.skill'
			p = t 'about.show_page.skill_inf'

			div class="progress-wrap"
				h3 .NET
				div class="progress"
					div class="progress-bar  color1" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 85%"
						span class="bar-width" 85%

			div class="progress-wrap"
				h4 Graphic Design
				div class="progress"
					div class="progress-bar color2" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 95%"
						span class="bar-width" 95%

			div class="progress-wrap"
				h4 Java
				div class="progress"
					div class="progress-bar color3" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 80%"
						span class="bar-width" 80%

			div class="progress-wrap"
				h4 Ruby, Ruby on Rails
				div class="progress"
					div class="progress-bar color4" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 90%"
						span class="bar-width" 90%

hr

section id="team"
    div class="container wow fadeInUp"
      div class="row"
        div class="col-md-12"
          h3 class="section-title" = t 'about.show_page.team'
          .section-title-divider
          p class="section-description" = t 'about.show_page.team_inf'
      
      div class="row"
        div class="col-md-3"
          div class="member"
            div class="pic"
            	=image_tag("team-1.jpg")
            h4 Walter White
            span Chief Executive Officer
            div class="social"
              a href=""
              	i class="fa fa-twitter"
              a href=""
              	i class="fa fa-facebook"
              a href=""
              	i class="fa fa-google-plus"
              a href=""
              	i class="fa fa-linkedin"

        div class="col-md-3"
          div class="member"
            div class="pic"
            	=image_tag("team-2.jpg")
            h4 Sarah Jhinson
            span Product Manager
            div class="social"
              a href=""
              	i class="fa fa-twitter"
              a href=""
              	i class="fa fa-facebook"
              a href=""
              	i class="fa fa-google-plus"
              a href=""
              	i class="fa fa-linkedin"
        
        div class="col-md-3"
          div class="member"
            div class="pic"
            	=image_tag("team-3.jpg")
            h4 William Anderson
            span CTO
            div class="social"
              a href=""
              	i class="fa fa-twitter"
              a href=""
              	i class="fa fa-facebook"
              a href=""
              	i class="fa fa-google-plus"
              a href=""
              	i class="fa fa-linkedin"
        
        div class="col-md-3"
          div class="member"
            div class="pic"
            	=image_tag("team-4.jpg")
            h4 Amanda Jepson
            span Accountant
            div class="social"
              a href=""
              	i class="fa fa-twitter"
              a href=""
              	i class="fa fa-facebook"
              a href=""
              	i class="fa fa-google-plus"
              a href=""
              	i class="fa fa-linkedin"

app/views/pages/contact.html.slim
div class="carousel fade-carousel slide" data-ride="carousel" data-interval="2200" id="bs-carousel"

  ol class="carousel-indicators"
    li data-target="#bs-carousel" data-slide-to="0" class="active"
    li data-target="#bs-carousel" data-slide-to="1"
  
  div class="carousel-inner"
    div class="item slides active"
      div class="slide-4"
      div class="hero"
        hgroup
            h1 = t 'contact.show_page.build'   
    div class="item slides"
      div class="slide-5"
      div class="hero"    
        hgroup
            h1 = t 'contact.show_page.office'  

section id="contact"
    div class="container wow fadeInUp"
      div class="row"
        div class="col-md-12"
          h3 class="section-title" = t 'contact.show_page.cont'  
          hr
      
      div class="row"
        div class="col-md-3 col-md-push-2"
          div class="info"
            div
              i class="glyphicon glyphicon-map-marker"
              p 
                | A108 Adam Street
                br New York, NY 535022
            
            div
              i class="glyphicon glyphicon-envelope"
              p info@example.com
            br
            div
              i class="glyphicon glyphicon-earphone"
              p +1 5589 55488 55

        
        div class="col-md-5 col-md-push-2"
          div class="form"
            div id="sendmessage" Your message has been sent. Thank you!
            div id="errormessage"
            form action="" method="post" role="form" class="contactForm"
                div class="form-group"
                  input type="text" name="name" class="form-control" id="name" placeholder="#{t'contact.show_page.name'}" data-rule="minlen:4" data-msg="Please enter at least 4 chars"
                  .validation
                div class="form-group"
                  input type="email" class="form-control" name="email" id="email" placeholder="#{t'contact.show_page.email'}" data-rule="email" data-msg="Please enter a valid email"
                  .validation
                div class="form-group"
                  input type="text" class="form-control" name="subject" id="subject" placeholder="#{t'contact.show_page.subj'}" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject"
                  .validation
                div class="form-group"
                  textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="#{t'contact.show_page.desc'}" placeholder="#{t'contact.show_page.desc'}"
                  .validation
                div class="text-center"
                  button type="submit" = t 'contact.show_page.send'

#google-map
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3024.8844088212463!2d-73.98975255333487!3d40.698543335037364!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a35da2fd673%3A0x218ed6cc00224ef8!2zQWRhbXMgU3QsIEJyb29rbHluLCBOWSAwNzAzMCwg0KHQv9C-0LvRg9GH0LXQvdGWINCo0YLQsNGC0Lgg0JDQvNC10YDQuNC60Lg!5e0!3m2!1suk!2sua!4v1489841068240" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/pages/event.html.slim
div class="container bg-overlay-events"
	div class="events-header container-fluid"
				h1
					strong Events

hr

div class="container"
	div class="row"
		div class="col-md-8 col-md-offset-2"
			div id="calendar"

hr

app/views/pages/home.html.slim
div class="animated_greeting"
	div class="content"
		div id="large-header" class="large-header"
			canvas id="demo-canvas"
			h1 class="main-title" 
				strong Code 
				span class="thin" star
				p = t 'home.show_page.slogan'
hr

div class="codrops-header container-fluid"
	h1 
		strong = t 'home.show_page.way'
		span = t 'home.show_page.way_desc'
hr
br
div class="container"
	div class="row"
		div class="col-sm-6 col-md-6"
			div class="services-wrap"
				div class="text-center"
					.fa.fa-rocket#rocket
				div class="services-body"
					h2 = t 'home.show_page.startup'
            		p = t 'home.show_page.startup_desc'
		div class="col-sm-6 col-md-6"
			div class="services-wrap"
				div class="text-center"
					.fa.fa-building-o#build
				div class="services-body"
					h2 = t 'home.show_page.commerce'
            		p = t 'home.show_page.commerce_desc'
		div class="col-sm-6 col-md-6"
			div class="services-wrap"
				div class="text-center"
					.fa.fa-heartbeat#heart
				div class="services-body"
					h2 = t 'home.show_page.health'
            		p = t 'home.show_page.health_desc'
        div class="col-sm-6 col-md-6"
			div class="services-wrap"
				div class="text-center"
					.fa.fa-globe#globe
				div class="services-body"
					h2 = t 'home.show_page.heavy'
            		p = t 'home.show_page.heavy_desc'					
hr
div id="about-bg"

	div class="container"
		div class="row"
			div class="about-bg-heading"
				h1 
					strong = t 'home.show_page.successful'
				p = t 'home.show_page.successful_p'

			div class=" col-xs-12 col-md-3"
				div class="about-bg-wrapper"
					span class="count"
						h1
							span class="border" 32
							| 15
					p = t 'home.show_page.happy'

			div class="col-xs-12 col-md-3"
				div class="about-bg-wrapper"
					span class="count"
						h1
							span class="border" 32
							| 15
					p = t 'home.show_page.proj'

			div class="col-xs-12 col-md-3"
				div class="about-bg-wrapper"
					span class="count"
						h1
							span class="border" 32
							| 15
					p = t 'home.show_page.bra'

			div class="col-xs-12 col-md-3"
				div class="about-bg-wrapper"
					span class="count"
						h1
							span class="border" 32
							| 15
					p = t 'home.show_page.team'

	div class="cover"

section id="testimonials"
    div class="container wow fadeInUp"
      div class="row"
        div class="col-md-12"
          h3 class="section-title" 
          	strong = t 'home.show_page.testimonial'
          hr
          p class="section-description" 
          	span = t 'home.show_page.see_test'
      
      div class="row"
        div class="col-md-3"
          div class="profile"
            div class="pic"=image_tag("client-1.jpg")
            h4 Saul Goodman
            span Envato Inc
        div class="col-md-9"
          div class="quote"
            b=image_tag("quote_sign_left.png") 
            = t 'home.show_page.test_1'
            small =image_tag("quote_sign_right.png")
      
      div class="row"
        div class="col-md-9"
          div class="quote"
            b=image_tag("quote_sign_left.png") 
            = t 'home.show_page.test_2'
            small =image_tag("quote_sign_right.png")
        div class="col-md-3"
          div class="profile"
            div class="pic"=image_tag("client-2.jpg")
            h4 Sara Wilsson
            span Microlancer Inc

hr

div id="client"
	div class="container"
		div class="row"
			div class="col-sm-4 col-md-2"
				span 
				= image_tag("client1.png")

			div class="col-sm-4 col-md-2"
				span
				= image_tag("client2.png")

			div class="col-sm-4 col-md-2"
				span
				= image_tag("client3.png")

			div class="col-sm-4 col-md-2"
				span
				= image_tag("client4.png")

			div class="col-sm-4 col-md-2"
				span
				= image_tag("client5.png")

			div class="col-sm-4 col-md-2"
				span
				= image_tag("client6.png")
hr

app/views/vacancies/edit.html.slim
div class="carousel fade-carousel slide" data-ride="carousel" data-interval="2200" id="bs-carousel"

  ol class="carousel-indicators"
    li data-target="#bs-carousel" data-slide-to="0" class="active"
    li data-target="#bs-carousel" data-slide-to="1"
  
  div class="carousel-inner"
    div class="item slides active"
      div class="slide-6"
      div class="hero"
        hgroup
            h1 Our main office building.

div class="codrops-header container-fluid"
	h1 
		strong Updating new Vacancy

= render 'form'

app/views/vacancies/new.html.slim
div class="container bg-overlay"

div class="codrops-header container-fluid"
	h1 
		strong Creating new Vacancy

= render 'form'